const affirmations = [
    "You are enough, just as you are ♡",
    "Your light shines, even when you can’t see it ♡",
    "Gosh Aqua, you're so soo strong ♡",
    "It’s okay to take things one small step at a time, slow & steady, you've got this Aquagirl ♡",
    "You are never alone, even in the quiet moments and I promise you that you never will be ♡",
    "Aqua you're so lovely your presence is a gift to the world ♡",
    "You deserve kindness, love, and peace and i promise you that your life will always never be this same way ♡",
    "Even in silence, your voice matters, i promise you that ♡",
    "Aqua you're are a beautiful soul with infinite strength who inspires so many ♡",
    "Small steps are still progress you're doing so well mhm ♡",
    "You matter so deeply so so much to us in our hearts Aqua ♡",
    "It’s okay to pause and breathe you're doing so well Aqua ♡",
    "You are so much more than you think ♡",
    "You are seen, you are heard, you are valued so soo much ♡",
    "Aqua, you are never 'too much' and you never will be ♡",
    "You're so sooo loved Aqua ♡",
    "You're so precious to us Aqua ♡",
    "Gosh Aqua, we're all so proud of you ♡",
    "I'm so grateful to have you as a friend, we all are ♡",
    "Aqua, you bring so so soo much happiness into the lives of those around you ♡",
    "Seeing you in the chat is like that little excitement of finding an extra Christmas gift under the tree ♡",
    "You're so lovely Aqua ♡",
    "Go get that Hot Chocolate which is waiting for you, you deserve it mhm ♡",
    "You're not alone Aqua and you never will be, that's a promise that I make to you ♡",
    "Aqua I promise you that all this hard work will pay of one day ♡",
    "Your voice matters ♡",
    "Aqua your smile is so precious its a gift to this world ♡",
    "You're such a beautiful and precious soul ♡",
    "Aqua your presence is cherished so so soo much in our hearts ♡",
    "Aqua, you're never 'not enough' ♡",
    "Gosh Aqua, you're such a treasure ♡",
    "Aqua, you're beautiful, both, inside and out and you're so so precious to us ♡",
    "Gosh you're so strong and powerful and you inspire sooo many mhm ♡",
    "You're an irreplaceable part of this world and of our lives ♡",
    "You are worthy of every good thing in life ♡",
    "To thos who know you, including me and so many others in the Haven, you're a gift to us ♡",
    "You are whole ♡",
    "You are loved beyond measure ♡",
    "Thank you for existing Aqua ♡",
    "You're as lovely as those little chunks of chocolate in mint chocolate ice cream that make it just perfect ♡",
    "You're as lovely as Apple Crumble & Salted Caramel Ice Cream ♡",
    "You make people smile the way just the way the thought of eating sushi does ♡",
];

function showAffirmation() {
    const randomIndex = Math.floor(Math.random() * affirmations.length);
    document.getElementById('affirmation').innerText = affirmations[randomIndex];
}
